### ISSUE TITLE
Does not work with jobs in folders

### ISSUE THREAD

**Issue by jf647** [jenkinsci/gogs-webhook-plugin#10]
When using the Cloudbees Folder plugin, the webhook cannot start jobs that are in folders.  The log reports:

WARNING: Job 'foo/bar' is not defined in Jenkins
Feb 19, 2017 10:00:19 PM org.jenkinsci.plugins.gogs.GogsWebHook exitWebHook
WARNING: Job 'foo/bar' is not defined in Jenkins
Feb 19, 2017 10:01:23 PM org.jenkinsci.plugins.gogs.GogsWebHook doIndex
WARNING: Job 'foo/job/bar' is not defined in Jenkins
Feb 19, 2017 10:01:23 PM org.jenkinsci.plugins.gogs.GogsWebHook exitWebHook
WARNING: Job 'foo/job/bar' is not defined in Jenkins

When I move this job to the root of my Jenkins server, it works properly.

In the webhook in gitea, I've tried using url-encoded and raw slashes to separate path elements with no observable change.  I suspect gitea is encoding it for me in the later case.  I've also tried putting 'job' as an element between the folder and the job, as this is what the Jenkins address bar shows, also without success.

**Comment by willemvd** [comment]
Tested this and I think you can just use "bar" as the job name in Gogs/Gitea, so:
/gogs-webhook/?job=bar

This also showed me a problem with the fact that we at the moment only look at the job.getName() .
If the name of a job is used in 2 different folders, it is possible that we cannot find the right job.
Will create a new PR to address this issue.

@jf647 could you confirm that only the job name is enough to get the stuff running?

**Comment by willemvd** [comment]
Think this can be closed since #12 is merged

**Comment by sanderv32** [comment]
#12 is merged :-)

**Comment by fuhbar** [comment]
@willemvd Yes, this works by just supplying the job name while using foldered jenkins setups.

**Comment by fuhbar** [comment]
@sanderv32 When will this change released? Or how do I use nightly builds or something?

**Comment by sanderv32** [comment]
@fuhbar You can get an artifact from the [JenkinsCI buildserver](https://jenkins.ci.cloudbees.com/job/plugins/job/gogs-webhook-plugin/) for the time being. Will try to release a the new version before the end of the week.
