### ISSUE TITLE
how to build pushing branch ?

### ISSUE THREAD

**Issue by xxxifan** [jenkinsci/gogs-webhook-plugin#17]
like push A branch to gogs, and jenkins start to build this branch instead of default branch set by jenkins?

**Comment by sanderv32** [comment]
#8 is stil open and probably this is what you want.

**Comment by S3NS4Ti0N** [comment]
@xxxifan @sanderv32 

I added PR https://github.com/jenkinsci/gogs-webhook-plugin/pull/20 for adding this functionality.
