### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kkolk** [jenkinsci/gogs-webhook-plugin#32]
There are some things that are currently affecting me in the version of the plugin you can download through Jenkins, which have been fixed in accepted pull requests over the past year, but there hasn't been a new version put out since last April.

Any plans to issue an updated release?

**Comment by christophe-mailfert** [comment]
any news ?

**Comment by christophe-mailfert** [comment]
@sanderv32 The current version of this plugin (https://wiki.jenkins.io/display/JENKINS/Gogs+Webhook+Plugin) does not accept pipeline jenkins (blue ocean)

Any news about a new version ?

**Comment by sanderv32** [comment]
Released version 1.0.11 today. Wiki page still needs to be updated.
