### ISSUE TITLE
Cant get the 1.0.12 new env variables (GOGS_REF and GOGS_BEFORE)  in pipeline. 

### ISSUE THREAD

**Issue by everccc** [jenkinsci/gogs-webhook-plugin#38]
Cant get the Version 1.0.12 new env variables (GOGS_REF and GOGS_BEFORE)  in pipeline. 

sh("printenv") show without GOGS_REF  and GOGS_BEFORE.
Am i missing something?

- Gogs version (or commit ref): 0.11.34.1122
- Jenkins version: 2.89.4
- other module all up to date

## Description

...

**Comment by sanderv32** [comment]
Under `Build Triggers` did you enable Gogs-Webhook?

**Comment by everccc** [comment]
You mean "Build when a change is pushed to Gogs" this ? 
Sorry for not notice it at first .  
and i create a small service to handle gogs webhook and call jenkins job with custom policy.So now i am
 not using this plugin  for now.

Thanks for replying. 
As gogs do not add filter of  webhook trigger by seperate branches .I think it  should be great that gogs-webhook-plugin can handle it .
