### ISSUE TITLE
Jenkins pipeline blue ocean with gogs-webhook-plugin

### ISSUE THREAD

**Issue by christophe-mailfert** [jenkinsci/gogs-webhook-plugin#39]
- Gogs version (or commit ref): 0.9.141.0211
- Jenkins version: 2.101
- Jenkins modules used in combination with gogs-webhook-plugin: blue-ocean, pipeline
- JSON Output of webhook: None Error 500

## Description
I'm looking for some documentation for running / configuring gogs-webhook-plugin with jenkins pipeline & blue ocean.

I tried webhook uri: 
- http://myjenkins/gogs-webhook/
- http://myjenkins/gogs-webhook/?job
- http://myjenkins/gogs-webhook/?job=

But nothing works.

Any documentation for pipeline ?

**Comment by christophe-mailfert** [comment]
Ok got an update :)

I got a new error:

Call
Request URL: http://jenkins.miodex.com/gogs-webhook/?job=pad-api
Request method: POST
Content-Type: application/json
X-Gogs-Delivery: e8afa794-9124-4584-9d94-48e380775868
X-Gogs-Event: push


Response:
Content-Length: 0
Date: Tue, 03 Apr 2018 16:12:30 GMT
Location: https://jenkins.miodex.com/gogs-webhook/?job=pad-api
Server: lighttpd/1.4.45

Any id why i'm redirect on https ?

This is an error on server configuration ?

Thx for advance.

**Comment by sanderv32** [comment]
Hi @christophe-mailfert. This is not the webhook redirecting you, but it looks like lighttpd is doing this.

**Comment by sanderv32** [comment]
@christophe-mailfert Any progress finding the cause of the redirect?

**Comment by christophe-mailfert** [comment]
@sanderv32 Yes that was a missconfiguration of lighttpd. 

Thx a lot. 

I close the ticket.

**Comment by sanderv32** [comment]
Ok, that can happen.
