### ISSUE TITLE
Job not found in version 1.0.7

### ISSUE THREAD

**Issue by sanderv32** [jenkinsci/gogs-webhook-plugin#4]
_Silox:_
> Seems like this change broke something in the ?job=jobname query filter. In 1.0.7, testing the webhook from Gogs resulted in a 404: "Job X is not defined in Jenkins", downgrading to 1.0.6 fixed this error.

**Comment by willemvd** [comment]
Found the problem, it only occurs when you have setup authorization.
When giving everybody all rights, the build will start.
See we forgot to do the ACL stuff in this part, like we do in 
https://github.com/jenkinsci/gogs-webhook-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gogs/GogsPayloadProcessor.java#L52-L53

I will create a new pull request to fix this

**Comment by sanderv32** [comment]
Ok, thats nice that you have found it 👍
Will try to merge it tonight but i'm not able to test it.

**Comment by nklmilojevic** [comment]
Hi, 

I'm also having the same problem with my Gogs and Jenkins. Hope that it'll be fixed soon.

**Comment by willemvd** [comment]
@sanderv32 you have merged #5 yesterday, but when will you release this?

**Comment by sanderv32** [comment]
I hope to release it this evening.

**Comment by sanderv32** [comment]
Just made release 1.0.8 with the fix @willemvd supplied. Now we'll have to wait before it's available in Jenkins.

**Comment by nklmilojevic** [comment]
Alright, everything works now. Thanks.

**Comment by willemvd** [comment]
@nklmilojevic agree 👍

**Comment by sanderv32** [comment]
Thanks guys! I will close this issue. :-)

**Comment by Silox** [comment]
Can confirm that it is fixed here too, thank you!

**Comment by ilyasotkov** [comment]
I have this issue with Gogs plugin 1.0.10. I use Gogs 0.11.29.0727 and Jenkins 2.84 . The response I get:
```
{"result":"ERROR","message":"Job _<< job name >>_ is not defined in Jenkins"}
```

**Comment by jmMeessen** [comment]
Hello @ilyasotkov
Thank you for reporting this. I will try to reproduce this and investigate.

For clarity, could you please open a separate issue for this.

/- Jmm

**Comment by jmMeessen** [comment]
Hello @ilyasotkov 
I was not able to reproduce your issue with Jenkins 2.84 and Gogs 0.11.29 (in the state available in the DockerHub images). I used for that the Automated Integration Tests I am working on.

When you have opened the adhoc ticket, can you describe what you try to achieve and how ?

/- Jmm
