### ISSUE TITLE
verson 1.0.15 webhook run ansible-playbook stuck

### ISSUE THREAD

**Issue by zibber2015** [jenkinsci/gogs-webhook-plugin#66]
The issue will be closed without any reasons if it does not satisfy any of following requirements:

- os: centos 7
- Gogs version (or commit ref): version 1.0.15
- Jenkins version: jenkins-2.235.5-1.1.noarch
- Jenkins modules used in combination 
   Ansible plugin  DingTalk

## 
0. jenkins job only has ansible-playbook script and dingtalk  notify
1. manual run jenkins job works fine
2. with webhook (gogs version 1.0.15) run job got stuck, task console nothing return,  jenkins server shut down also
3. gogs version 1.0.14 works fine

**Comment by sanderv32** [comment]
Can you please provide a Stacktrace from the Jenkins logfile
