### ISSUE TITLE
Create new Job on receiving create hook.

### ISSUE THREAD

**Issue by KangoV** [jenkinsci/gogs-webhook-plugin#7]
It would be brilliant if this plugin could create a new job (based upon build for master) for a new branch in GOGS. The name could perhaps be configurable, but this would not matter. GOGS already supports sending a hook to a url on a branch and tag create.

**Comment by sanderv32** [comment]
@KangoV Can you give me an example of what you want to achieve, because at the moment i can't imagine what you want to do.

**Comment by KangoV** [comment]
@sanderv32 The idea is to have a new job created in jenkins to build a newly created branch in gogs. If we already have a job in Jenkins which is building master, then a new job should be created based upon the master build but building the branch instead. 

I hope that makes sense.

**Comment by sanderv32** [comment]
I get your idea but this can be done with the pipeline plugin. Personally i want to keep this plugin simple and it should cooperate with other plugins like for example the pipeline plugin.
