### ISSUE TITLE
Cannot find how to access payload

### ISSUE THREAD

**Issue by FGM** [jenkinsci/gogs-webhook-plugin#8]
I have set up the plugin on Jenkins and created the webhook. My jobs are triggered normally, but the only information I have access to appears to be the following:

    X-Gogs-Delivery: 580aada0-d020-45a7-9177-37c398e0ac99
    X-Gogs-Event: push

Even looking at the plugin source code, I can't see where it would pass the payload to Jenkins. How then are jobs supposed to obtain the information they need, like - at least - the branch name on which the push occurred ? Or what am I missing ?

When I push to some branch, events are correctly sent to Jenkins, but besides the headers above, the Git pluging always returns the same `GIT_COMMIT` and `GIT_BRANCH` values, which are not the ones included in the latest push, but always a constant other set of values.

**Comment by sanderv32** [comment]
At the moment we don't pass payload data to Jenkins, but probably this is something we can build in easily. Will investigate this.

**Comment by FGM** [comment]
Wondering: if you did not feel the need to include that feature, how do you use the plugin to trigger the appropriate builds in Jenkins ? I thought the git plugin would poll git and find the latest commit not yet tested, but this does not appear to be the case: the SHA1 returned is not the most recent, nor even on the most recently modified branch.

**Comment by sanderv32** [comment]
It's a webhook so it doesn't poll your repo for changes. Your repo should post to this webhook the job it wants to execute and than that job will run. This webhook is not different than all the other webhooks in the Jenkins plugin repo.

**Comment by fabienjuif** [comment]
I'd like to use this plugin in this way, and I think it is the same way than @FGM 
 - I push a commit on my Gogs server
 - Gogs calls jenkins
 - Jenkins now the `commit hash` so : 
   - It pulls the source code from this `commit hash`
   - It builds it (with a Jenkinsfile)

So I have only **one** job that can run with **multiple branches**.

**Comment by sanderv32** [comment]
Ok this is clear and also doable. I will create a new option in the plugin which takes the data from the payload because otherwise it will break for the way other users work at the moment.

**Comment by FGM** [comment]
@fabienjuif thanks, you explained it better than I did, this is exactly the idea. Using git flow, we create multiple branches per day so it wouldn't make sense to have one job per branch: this only works for long-lived branches, not feature/hotfix branches like these.

**Comment by fabienjuif** [comment]
Nice @sanderv32 :+1: thank you.

**Comment by KangoV** [comment]
This is the functionality we need also. Question though, how would Jenkins show the results of multiple branch build for a single job?

**Comment by sanderv32** [comment]
@KangoV The webhook will in this case just modify your job, so the results will be in the same job.

**Comment by FGM** [comment]
@KangoV In my case this job would be mostly useful to notify the dev authoring the commit after running the (long-running) test suite. I would have normal fixed-branch jobs for long-lasting branches like develop/master.

**Comment by sanderv32** [comment]
At the moment the development branch exposes the "ref" and "after" key from the JSON payload. So now it's possible to use GOGS_REF and GOGS_AFTER as environment variables which you can use in your "Branch to build". If someone can test it i would be very happy :-)

**Comment by sanderv32** [comment]
You can download the latest snapshot from: https://jenkins.ci.cloudbees.com/job/plugins/job/gogs-webhook-plugin/6/org.jenkins-ci.plugins$gogs-webhook/

**Comment by tkisme** [comment]
refer #11

**Comment by sanderv32** [comment]
This branch needs to be tested before i'm going to make a pull request and merge it. Can someone have a look if this works?

**Comment by xXpc-freakXx** [comment]
I have a problem with a multibranch pipeline.
For example, the name of the multibranch pipeline is "test" and in this pipeline i have the branches "master" and "develop".
If i set the web hook url to "https://<<jenkins-server>>/gogs-webhook/?job=test", then he can't find the pipeline on jenkins.
When i rename the job on the url to "test/master" or "test/develop", then is the hook successfull. 

To fix it, you can read the "ref" property of the post data and merge the defined job name with the cotained branch.

**Comment by S3NS4Ti0N** [comment]
@xXpc-freakXx I added a PR for adding this functionality.

https://github.com/jenkinsci/gogs-webhook-plugin/pull/20

**Comment by willemvd** [comment]
@sanderv32 could you merge master into development? Maybe I will be able to test it but not without the current features

**Comment by tkisme** [comment]
You can download the latest snapshot from: https://jenkins.ci.cloudbees.com/job/plugins/job/gogs-webhook-plugin/29/org.jenkins-ci.plugins$gogs-webhook/

**Comment by sanderv32** [comment]
@tkisme Can you share the code with us? @willemvd Tried to master into development, but the development is way behind and it's not that easy to implement that code again.

**Comment by tkisme** [comment]
https://github.com/jenkinsci/gogs-webhook-plugin/pull/20/files do you mean this?

**Comment by S3NS4Ti0N** [comment]
@sanderv32 
When will my pr get merged ?

**Comment by sanderv32** [comment]
@S3NS4Ti0N I want to merge it but as we don't have unit test at the moment we have to be sure that it won't break the plugin.

**Comment by S3NS4Ti0N** [comment]
Uhm ... Then what about testing it ?

I have it working like this without any problems.

**Comment by tkisme** [comment]
@S3NS4Ti0N please write unit tests

**Comment by sanderv32** [comment]
@S3NS4Ti0N because this can potentially break even the basics of the plugin, i will merge this if more people will test you PR. If it works fine i will merge it, and for the next release unit tests should be written.

**Comment by sanderv32** [comment]
Sorry for the delay, but did the PR and waiting for the rebase of the unit test. After that we can release version 1.0.12

**Comment by pjmeisch-cc** [comment]
any progress on this to get multibranch projects working?

**Comment by urusha** [comment]
Could you please add https://github.com/jenkinsci/gogs-webhook-plugin/commit/316e62263d1d76cdbe58a807d88970acd5ba24c3 to master, since the build number 6 with this feature is unavailable now (rotated?).

**Comment by maxep** [comment]
Will it be released soon? I also need the multibranch pipeline feature.
Thanks!

**Comment by Crayon2000** [comment]
@maxep, for Pipeline / Multibranch Pipeline project I use a Webhook with a **Payload URL** like this:
`https://jenkinsserver.com/git/notifyCommit?url=https://gogsserver.com/org/project.git`
This will NOT trigger a build on a specific project, but will tell all project using the repository to Scan for changes. If changes are found, then it will trigger the build.

In the **When should this webhook be triggered** section I choose **Let me choose what I need** with these:
- Create
- Delete
- Push

Pull Request will not work :(

More information here: https://wiki.jenkins.io/display/JENKINS/Git+Plugin#GitPlugin-Pushnotificationfromrepository

I hope this can help you.

**Comment by sanderv32** [comment]
Have released version 1.0.11. Changelog on the wiki page is not yet updated (although I can see it). Because of lack of time it's not 100% tested.

**Comment by urusha** [comment]
Still no support for payload via environment :(

**Comment by sanderv32** [comment]
If you refer to the development branch, then that's correct that the environment variables aren't there at the moment. Maybe in the weekend I have some time to merge it in the current master but I can't make a promise.

**Comment by sanderv32** [comment]
@urusha Development branch is up to date with all the changes in the master. Pipeline is not green at the moment but you can already download the development hpi [here](https://ci.jenkins.io/job/Plugins/job/gogs-webhook-plugin/job/development/3/artifact/target/gogs-webhook.hpi).

**Comment by urusha** [comment]
Thanks for your work! Tried that one, got `{"result":"ERROR","message":"Job 'jobname' is not defined in Jenkins"}` when triggering (with and without new GOGs checkbox in 'Build Triggers' section). So, can not tell if ENV works.

**Comment by YuukanOO** [comment]
v1.0.11 seems to work for me 👍 !

**Comment by bastienlemaitre** [comment]
Works for me too ! :)

**Comment by maxep** [comment]
Works with multibranch pipeline? I still got the same error as @urusha 
`{"result":"ERROR","message":"Job '...' is not defined in Jenkins"}`

**Comment by YuukanOO** [comment]
I just have to click on **Scan Multibranch Pipeline Log** in Jenkins for it to create the job associated with the branch and when webhook `POST` to `http://jenkins/gogs-webhook/?job=MyJob`, it runs the pushed branch.

**Comment by maxep** [comment]
My bad, I was testing with master but my pipeline is not merged yet :) thanks @YuukanOO

**Comment by willemvd** [comment]
@sanderv32 today we started using the GOGS_REF variable with the development branch hpi and that is working great!

**Comment by sanderv32** [comment]
@willemvd Thanks for the feedback! Will create a release from the development branch.

**Comment by sanderv32** [comment]
Development branch is merged into master and released version 1.0.12.

**Comment by urusha** [comment]
@sanderv32  Environment seems to work fine, but even with the last release I still got `{"result":"ERROR","message":"Job 'dirname/jobname' is not defined in Jenkins"}` if the job is placed in folder. Without folder all is ok. Should I file new report?

**Comment by sanderv32** [comment]
@urusha If this didn't work in the past, version 1.0.12 will not fix this then please create a new issue for that so that we can create a version for that one.

**Comment by urusha** [comment]
@sanderv32 This worked before 1.0.12. But doesn't work with 1.0.12

**Comment by sanderv32** [comment]
@urusha Will create a new issue for this.
