### ISSUE TITLE
The branch is ignored

### ISSUE THREAD

**Issue by marcopiraccini** [jenkinsci/gogs-webhook-plugin#9]
I setup gogs + jenkins + this plugin.
I have a job that builds `master`. 
Currently, when I push a commit in `test` branch, jenkins build is triggered, and `master` branch is build. 
There's a way to have a more "smarter" trigger, that specify the branch to avoid that?

**Comment by sanderv32** [comment]
You can specify which branch you want to checkout in your job. If this is not what you're looking for then you probably experiencing issue #8
